package turn

import (
	"errors"
	"fmt"
	"sync"

	"buk-yutnori/internal/domain"
	"buk-yutnori/internal/domain/room"
)

var (
	// ErrInvalidMachineConfig identifies invalid immutable turn configuration.
	ErrInvalidMachineConfig = errors.New("invalid turn machine configuration")

	// ErrInvalidTransition identifies an action that is not accepted in the current phase.
	ErrInvalidTransition = errors.New("invalid turn transition")

	// ErrUnexpectedThrowOrigin identifies a result generated for a different throw cause.
	ErrUnexpectedThrowOrigin = errors.New("unexpected result origin")

	// ErrWrongTurnPlayer identifies a result generated by someone other than the current player.
	ErrWrongTurnPlayer = errors.New("result generated by wrong turn player")

	// ErrSelectedTokenMismatch identifies an action for a token other than the selected token.
	ErrSelectedTokenMismatch = errors.New("selected result token mismatch")

	// ErrInvalidOutcome identifies contradictory movement or Buk resolution flags.
	ErrInvalidOutcome = errors.New("invalid turn resolution outcome")
)

// Snapshot is a copy of all state owned by a Machine.
type Snapshot struct {
	PlayerID            domain.PlayerID
	Phase               domain.TurnPhase
	RequiredInput       domain.RequiredInput
	ExpectedThrowOrigin domain.ResultOrigin
	SelectedTokenID     domain.ResultTokenID
	ResultQueue         []ResultToken
}

// MoveOutcome contains only the movement-engine decisions needed for turn flow.
type MoveOutcome struct {
	CaptureExtraThrow bool
	MatchEnded        bool
}

// Validate rejects outcomes that cannot both take effect.
func (outcome MoveOutcome) Validate() error {
	if outcome.CaptureExtraThrow && outcome.MatchEnded {
		return fmt.Errorf("%w: capture extra throw cannot follow match end", ErrInvalidOutcome)
	}
	return nil
}

// BukOutcome contains only the Buk-engine decisions needed for turn flow.
type BukOutcome struct {
	NoCandidate       bool
	CaptureExtraThrow bool
	MatchEnded        bool
}

// Validate rejects mutually exclusive Buk outcomes.
func (outcome BukOutcome) Validate() error {
	if outcome.NoCandidate && (outcome.CaptureExtraThrow || outcome.MatchEnded) {
		return fmt.Errorf("%w: no-candidate Buk cannot move, capture, or end a match", ErrInvalidOutcome)
	}
	if outcome.CaptureExtraThrow && outcome.MatchEnded {
		return fmt.Errorf("%w: capture extra throw cannot follow match end", ErrInvalidOutcome)
	}
	return nil
}

// Machine coordinates the pure phase and result-queue rules for one turn.
//
// Movement legality, route calculation, capture policy, victory, and Buk
// candidate resolution remain outside this type. Their resolved outcomes are
// supplied through the explicit completion methods.
type Machine struct {
	mutex sync.RWMutex

	playerID       domain.PlayerID
	movementOrder  room.MovementOrder
	yutMoExtra     bool
	phase          domain.TurnPhase
	requiredInput  domain.RequiredInput
	expectedOrigin domain.ResultOrigin
	selectedID     domain.ResultTokenID
	queue          *ResultQueue
}

// NewMachine creates a turn in the canonical turn_start phase.
func NewMachine(playerID domain.PlayerID, settings room.Settings) (*Machine, error) {
	if err := playerID.Validate(); err != nil {
		return nil, fmt.Errorf("%w: player_id: %w", ErrInvalidMachineConfig, err)
	}
	if err := settings.Validate(); err != nil {
		return nil, fmt.Errorf("%w: room settings: %w", ErrInvalidMachineConfig, err)
	}
	queue, err := NewResultQueue()
	if err != nil {
		return nil, fmt.Errorf("%w: result queue: %w", ErrInvalidMachineConfig, err)
	}
	return &Machine{
		playerID:      playerID,
		movementOrder: settings.MovementOrder,
		yutMoExtra:    settings.YutMoExtraThrow,
		phase:         domain.TurnStart,
		requiredInput: domain.InputNone,
		queue:         queue,
	}, nil
}

// Snapshot returns an atomic copy of the turn phase, pending decisions, and queue.
func (machine *Machine) Snapshot() Snapshot {
	machine.mutex.RLock()
	defer machine.mutex.RUnlock()
	return Snapshot{
		PlayerID:            machine.playerID,
		Phase:               machine.phase,
		RequiredInput:       machine.requiredInput,
		ExpectedThrowOrigin: machine.expectedOrigin,
		SelectedTokenID:     machine.selectedID,
		ResultQueue:         machine.queue.Snapshot(),
	}
}

// Start advances turn_start to the initial wait_throw decision.
func (machine *Machine) Start() error {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnStart, "start turn"); err != nil {
		return err
	}
	machine.setState(
		domain.TurnWaitThrow,
		domain.InputThrow,
		domain.ResultOriginInitialThrow,
		"",
	)
	return nil
}

// BeginThrow accepts the pending throw input and returns its canonical origin.
func (machine *Machine) BeginThrow() (domain.ResultOrigin, error) {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnWaitThrow, "begin throw"); err != nil {
		return "", err
	}
	origin := machine.expectedOrigin
	machine.setState(domain.TurnThrowingChain, domain.InputNone, origin, "")
	return origin, nil
}

// RecordThrow appends a server-generated result and advances the throwing chain.
func (machine *Machine) RecordThrow(token ResultToken) error {
	if err := token.Validate(); err != nil {
		return err
	}

	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnThrowingChain, "record throw"); err != nil {
		return err
	}
	if token.Origin != machine.expectedOrigin {
		return fmt.Errorf(
			"%w: got %q, want %q",
			ErrUnexpectedThrowOrigin,
			token.Origin,
			machine.expectedOrigin,
		)
	}
	if token.GeneratedByPlayerID != machine.playerID {
		return fmt.Errorf(
			"%w: got %q, want %q",
			ErrWrongTurnPlayer,
			token.GeneratedByPlayerID,
			machine.playerID,
		)
	}
	if err := machine.queue.Append(token); err != nil {
		return err
	}

	switch {
	case machine.yutMoExtra && token.Result == domain.YutYut:
		machine.setState(
			domain.TurnWaitThrow,
			domain.InputThrow,
			domain.ResultOriginYutExtra,
			"",
		)
	case machine.yutMoExtra && token.Result == domain.YutMo:
		machine.setState(
			domain.TurnWaitThrow,
			domain.InputThrow,
			domain.ResultOriginMoExtra,
			"",
		)
	default:
		machine.setState(domain.TurnResolveQueue, domain.InputNone, "", "")
	}
	return nil
}

// ResolveQueue advances resolve_queue to the next canonical decision or automatic step.
func (machine *Machine) ResolveQueue() error {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnResolveQueue, "resolve queue"); err != nil {
		return err
	}
	available, err := machine.queue.Available(machine.movementOrder)
	if err != nil {
		return err
	}
	if len(available) == 0 {
		machine.setState(domain.TurnEnd, domain.InputNone, "", "")
		return nil
	}
	if available[0].Result == domain.YutBuk {
		machine.setState(domain.TurnResolveBuk, domain.InputNone, "", available[0].ID)
		return nil
	}
	if len(available) == 1 {
		machine.setState(
			domain.TurnWaitPieceSelection,
			domain.InputSelectPiece,
			"",
			available[0].ID,
		)
		return nil
	}
	machine.setState(domain.TurnWaitResultSelection, domain.InputSelectResult, "", "")
	return nil
}

// SelectResult accepts one token exposed by free movement order.
func (machine *Machine) SelectResult(id domain.ResultTokenID) error {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnWaitResultSelection, "select result"); err != nil {
		return err
	}
	available, err := machine.queue.Available(machine.movementOrder)
	if err != nil {
		return err
	}
	for _, token := range available {
		if token.ID == id && token.Result != domain.YutBuk {
			machine.setState(
				domain.TurnWaitPieceSelection,
				domain.InputSelectPiece,
				"",
				id,
			)
			return nil
		}
	}
	return fmt.Errorf("%w: %q", ErrResultTokenNotAvailable, id)
}

// PieceSelected advances to route selection or directly to move application.
//
// The caller validates the piece and reports whether that move has a route choice.
func (machine *Machine) PieceSelected(id domain.ResultTokenID, routeRequired bool) error {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnWaitPieceSelection, "select piece"); err != nil {
		return err
	}
	if err := machine.requireSelected(id); err != nil {
		return err
	}
	if routeRequired {
		machine.setState(
			domain.TurnWaitRouteSelection,
			domain.InputSelectRoute,
			"",
			id,
		)
		return nil
	}
	machine.setState(domain.TurnApplyMove, domain.InputNone, "", id)
	return nil
}

// RouteSelected advances an externally validated route choice to move application.
func (machine *Machine) RouteSelected(id domain.ResultTokenID) error {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnWaitRouteSelection, "select route"); err != nil {
		return err
	}
	if err := machine.requireSelected(id); err != nil {
		return err
	}
	machine.setState(domain.TurnApplyMove, domain.InputNone, "", id)
	return nil
}

// MoveApplied marks the externally computed movement as committed for rule resolution.
func (machine *Machine) MoveApplied(id domain.ResultTokenID) error {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnApplyMove, "apply move"); err != nil {
		return err
	}
	if err := machine.requireSelected(id); err != nil {
		return err
	}
	machine.setState(domain.TurnResolveStackCaptureFinish, domain.InputNone, "", id)
	return nil
}

// CompleteMove consumes the selected token after stack, capture, and finish resolution.
func (machine *Machine) CompleteMove(id domain.ResultTokenID, outcome MoveOutcome) error {
	if err := outcome.Validate(); err != nil {
		return err
	}

	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnResolveStackCaptureFinish, "complete move"); err != nil {
		return err
	}
	if err := machine.requireSelected(id); err != nil {
		return err
	}
	if _, err := machine.queue.Consume(id, machine.movementOrder); err != nil {
		return err
	}
	machine.advanceAfterResolution(outcome.CaptureExtraThrow, outcome.MatchEnded)
	return nil
}

// DiscardUnusableResult consumes only the selected ordinary token and resumes the queue.
//
// The caller is responsible for determining that no legal piece can use it.
func (machine *Machine) DiscardUnusableResult(id domain.ResultTokenID) error {
	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnWaitPieceSelection, "discard unusable result"); err != nil {
		return err
	}
	if err := machine.requireSelected(id); err != nil {
		return err
	}
	if _, err := machine.queue.Consume(id, machine.movementOrder); err != nil {
		return err
	}
	machine.setState(domain.TurnResolveQueue, domain.InputNone, "", "")
	return nil
}

// CompleteBuk consumes the selected head Buk after external automatic resolution.
func (machine *Machine) CompleteBuk(id domain.ResultTokenID, outcome BukOutcome) error {
	if err := outcome.Validate(); err != nil {
		return err
	}

	machine.mutex.Lock()
	defer machine.mutex.Unlock()
	if err := machine.requirePhase(domain.TurnResolveBuk, "complete Buk"); err != nil {
		return err
	}
	if err := machine.requireSelected(id); err != nil {
		return err
	}
	if _, err := machine.queue.Consume(id, machine.movementOrder); err != nil {
		return err
	}
	if outcome.NoCandidate {
		machine.setState(domain.TurnEnd, domain.InputNone, "", "")
		return nil
	}
	machine.advanceAfterResolution(outcome.CaptureExtraThrow, outcome.MatchEnded)
	return nil
}

func (machine *Machine) advanceAfterResolution(captureExtra, matchEnded bool) {
	switch {
	case matchEnded:
		machine.setState(domain.TurnMatchEnd, domain.InputNone, "", "")
	case captureExtra:
		machine.setState(
			domain.TurnWaitThrow,
			domain.InputThrow,
			domain.ResultOriginCaptureExtra,
			"",
		)
	default:
		machine.setState(domain.TurnResolveQueue, domain.InputNone, "", "")
	}
}

func (machine *Machine) requirePhase(expected domain.TurnPhase, action string) error {
	if machine.phase != expected {
		return fmt.Errorf(
			"%w: cannot %s in %q; want %q",
			ErrInvalidTransition,
			action,
			machine.phase,
			expected,
		)
	}
	return nil
}

func (machine *Machine) requireSelected(id domain.ResultTokenID) error {
	if machine.selectedID != id {
		return fmt.Errorf(
			"%w: got %q, want %q",
			ErrSelectedTokenMismatch,
			id,
			machine.selectedID,
		)
	}
	return nil
}

func (machine *Machine) setState(
	phase domain.TurnPhase,
	input domain.RequiredInput,
	origin domain.ResultOrigin,
	selected domain.ResultTokenID,
) {
	machine.phase = phase
	machine.requiredInput = input
	machine.expectedOrigin = origin
	machine.selectedID = selected
}
